use serde::{Deserialize, Serialize};

use crate::id::{ChannelMarker, Id};

use self::{
    embed::Embed, interactions::Interactions, masquerade::Masquerade,
    system_message::SystemMessageType,
};

use super::{webhook::MessageWebhook, Channel};

pub mod data;
pub mod embed;
pub mod interactions;
pub mod masquerade;
pub mod reply;
pub mod system_message;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    /// Unique Id
    #[serde(rename = "_id")]
    pub id: String,
    /// Unique value generated by client sending this message
    #[serde(rename = "nonce", default, skip_serializing_if = "Option::is_none")]
    pub nonce: Option<Option<String>>,
    /// Resolved channel object
    #[serde(rename = "channel")]
    pub channel: Id<ChannelMarker>,
    /// Id of the user or webhook that sent this message
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "webhook", default, skip_serializing_if = "Option::is_none")]
    pub webhook: Option<Option<Box<MessageWebhook>>>,
    /// Message content
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    #[serde(rename = "system", default, skip_serializing_if = "Option::is_none")]
    pub system: Option<Option<Box<SystemMessageType>>>,
    /// Array of attachments
    #[serde(rename = "attachments", default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::attachment::File>>>,
    /// ISO8601 formatted timestamp
    #[serde(rename = "edited", default, skip_serializing_if = "Option::is_none")]
    pub edited: Option<Option<String>>,
    /// Attached embeds to this message
    #[serde(rename = "embeds", default, skip_serializing_if = "Option::is_none")]
    pub embeds: Option<Option<Vec<Embed>>>,
    /// Array of user ids mentioned in this message
    #[serde(rename = "mentions", default, skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Option<Vec<String>>>,
    /// Array of message ids this message is replying to
    #[serde(rename = "replies", default, skip_serializing_if = "Option::is_none")]
    pub replies: Option<Option<Vec<String>>>,
    /// Hashmap of emoji IDs to array of user IDs
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<::std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "interactions", skip_serializing_if = "Option::is_none")]
    pub interactions: Option<Box<Interactions>>,
    #[serde(rename = "masquerade", default, skip_serializing_if = "Option::is_none")]
    pub masquerade: Option<Option<Box<Masquerade>>>,
}

// @TODO: Implement a caching system for http requests
// impl Message {
//     #[inline]
//     pub async fn channel(&self, http: impl AsRef<Http>) -> Result<Channel> {
//        self.channel.get_channel(http).await
//     }

//     #[inline]
//     pub async fn delete(&self, http: impl AsRef<Http>) -> Result<()> {
//         self.channel.delete_message(http, self._id).await
//     }
// }

#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct PartialMessage {
   /// Unique Id
    #[serde(rename = "_id", default, skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    /// Unique value generated by client sending this message
    #[serde(rename = "nonce", default, skip_serializing_if = "Option::is_none")]
    pub nonce: Option<Option<String>>,
    /// Id of the channel this message was sent in
    #[serde(rename = "channel", default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    /// Id of the user or webhook that sent this message
    #[serde(rename = "author", default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "webhook", default, skip_serializing_if = "Option::is_none")]
    pub webhook: Option<Option<Box<MessageWebhook>>>,
    /// Message content
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    #[serde(rename = "system", default, skip_serializing_if = "Option::is_none")]
    pub system: Option<Option<Box<SystemMessageType>>>,
    /// Array of attachments
    #[serde(rename = "attachments", default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<crate::attachment::File>>>,
    /// ISO8601 formatted timestamp
    #[serde(rename = "edited", default, skip_serializing_if = "Option::is_none")]
    pub edited: Option<Option<String>>,
    /// Attached embeds to this message
    #[serde(rename = "embeds", default, skip_serializing_if = "Option::is_none")]
    pub embeds: Option<Option<Vec<Embed>>>,
    /// Array of user ids mentioned in this message
    #[serde(rename = "mentions", default, skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Option<Vec<String>>>,
    /// Array of message ids this message is replying to
    #[serde(rename = "replies", default, skip_serializing_if = "Option::is_none")]
    pub replies: Option<Option<Vec<String>>>,
    /// Hashmap of emoji IDs to array of user IDs
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<::std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "interactions", skip_serializing_if = "Option::is_none")]
    pub interactions: Option<Box<Interactions>>,
    #[serde(rename = "masquerade", default, skip_serializing_if = "Option::is_none")]
    pub masquerade: Option<Option<Box<Masquerade>>>,
}
